/**
 * Read-only adapter operations. The gateway kicks the outbox worker after
 * every successful NON-read operation, so this set is an explicit allowlist:
 * any operation not listed here is treated as a write and schedules a kick.
 * When a new registry operation is added, classify it here — the registry
 * coverage test fails if a read-like name is missing, and an unlisted write
 * safely defaults to kicking.
 */
const READ_OPERATION_NAMES: ReadonlySet<string> = new Set([
  "admissions.enrollmentReference",
  "admissions.listMine",
  "admissions.reviewerDirectory",
  "admissions.staffByRef",
  "admissions.staffQueue",
  "audit.list",
  "audit.listPage",
  "config.admissions",
  "config.read",
  "content.authorDirectory",
  "content.list",
  "content.listDownloads",
  "context.family",
  "context.staff",
  "dataExports.healthCheck",
  "dataExports.healthSnapshot",
  "dataExports.healthSnapshots",
  "dataExports.list",
  "dataExports.listCatalog",
  "dataExports.listPaginated",
  "dataImports.getBatch",
  "dataImports.listBatchesPaginated",
  "dataImports.listIssuesPaginated",
  "dataImports.listMappingTemplates",
  "dataImports.listResolutions",
  "dataImports.preview",
  "dataImports.report",
  "deliveries.list",
  "documents.get",
  "documents.list",
  "documents.listPage",
  "enrollment.readiness",
  "finance.getAttempt",
  "finance.listAdjustments",
  "finance.listAllAttempts",
  "finance.listAllReceipts",
  "finance.listAttempts",
  "finance.listInvoices",
  "finance.listReceipts",
  "finance.listReconciliationRuns",
  "finance.listRefunds",
  "guardianClaims.preview",
  "guardians.adminList",
  "identity.hasApplicant",
  "identity.hasStaff",
  "jobs.listMine",
  "jobs.retentionStatus",
  "jobs.staffQueue",
  "jobs.vacancies",
  "links.capabilities",
  "links.get",
  "links.listMine",
  "links.listPage",
  "notifications.list",
  "notifications.unreadCount",
  "results.examDefinitions",
  "results.getBatch",
  "results.getRelease",
  "results.listBatches",
  "results.listCorrections",
  "results.listPublications",
  "results.listReleases",
  "results.listVersions",
  "results.releaseCandidates",
  "schoolSetup.read",
  "settings.read",
  "settings.readLatest",
  "staff.profilesList",
  "support.list",
  "teachingStaff.list",
  "timetable.effective",
  "timetable.listDateSheets",
  "timetable.listOverrides",
  "timetable.listVersions",
  "timetable.validateDraft",
  "users.list",
]);

export function isReadOperation(name: string): boolean {
  return READ_OPERATION_NAMES.has(name);
}
