/**
 * PDF generation adapter (plan.md §6 Documents, §10 provider adapters).
 *
 * Resolves every field FROM the authoritative database records — never from
 * caller payloads — then renders reproducible documents. Storage upload is a
 * future boundary: generated bytes are returned to the outbox worker together
 * with safe metadata; a `documents` row with a reserved private `object_key`
 * is recorded so a Storage adapter can attach the object later without a
 * schema change.
 */

import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "@/lib/supabase/database.types";
import {
  REPORT_CARD_TEMPLATE_VERSION,
  RECEIPT_TEMPLATE_VERSION,
  renderReportCardPdf,
  renderReceiptPdf,
} from "@/lib/pdf/render";

export type GeneratedPdf = {
  bytes: Uint8Array;
  templateVersion: string;
  documentType: "receipt" | "report_card";
  checksum: string;
  sizeBytes: number;
  sourceRecordId: string;
  sourceReference: string;
  ownerDomain: "invoice" | "student";
  ownerRecordId: string;
  safeFilename: string;
};

export class PdfTransientError extends Error {}

function checksumOf(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

type ReceiptRecord = {
  id: string;
  reference: string;
  issued_at: string;
  invoices: {
    id: string;
    reference: string;
    status: string;
    student_id: string | null;
    applicant_ref: string | null;
    invoice_items: Array<{ label: string; amount_paise: number; kind: string }>;
  } | null;
  payments: {
    provider_txn_id: string;
    method: string | null;
    amount_paise: number;
    payment_allocations: Array<{ amount_paise: number; label: string | null }>;
  } | null;
};

async function resolveReceipt(
  admin: SupabaseClient<Database>,
  receiptRef: string,
): Promise<ReceiptRecord> {
  const { data, error } = await admin
    .from("receipts")
    .select(
      "id, reference, issued_at, invoices(id, reference, status, student_id, applicant_ref, invoice_items(label, amount_paise, kind)), payments(provider_txn_id, method, amount_paise, payment_allocations(amount_paise, invoices(reference)))",
    )
    .eq("reference", receiptRef)
    .maybeSingle();
  if (error !== null) throw new PdfTransientError(`receipt lookup failed: ${error.message}`);
  if (data === null) throw new Error(`Permanent: receipt ${receiptRef} not found`);
  return data as unknown as ReceiptRecord;
}

async function payerLabelFor(
  admin: SupabaseClient<Database>,
  record: ReceiptRecord,
): Promise<{ payerLabel: string; studentLabel: string }> {
  if (record.invoices?.applicant_ref !== null && record.invoices?.applicant_ref !== undefined) {
    const { data } = await admin
      .from("admission_applications")
      .select("reference, parent_name, student_name")
      .eq("reference", record.invoices.applicant_ref)
      .maybeSingle();
    return {
      payerLabel: data?.parent_name ?? "Applicant guardian",
      studentLabel: data?.student_name ?? record.invoices.applicant_ref,
    };
  }
  if (record.invoices?.student_id !== null && record.invoices?.student_id !== undefined) {
    const { data } = await admin
      .from("students")
      .select("reference, people(display_name)")
      .eq("id", record.invoices.student_id)
      .maybeSingle();
    return {
      payerLabel: "Linked guardian on record",
      studentLabel: data?.people?.display_name ?? data?.reference ?? "Student",
    };
  }
  return { payerLabel: "On record", studentLabel: "Student" };
}

export async function generateReceiptPdf(
  admin: SupabaseClient<Database>,
  receiptRef: string,
): Promise<GeneratedPdf> {
  const record = await resolveReceipt(admin, receiptRef);
  const invoice = record.invoices;
  if (invoice === null || record.payments === null) {
    throw new Error(`Permanent: receipt ${receiptRef} has no settled invoice/payment evidence`);
  }
  if (typeof invoice.id !== "string" || invoice.id.length === 0) {
    throw new Error(`Permanent: receipt ${receiptRef} has no invoice owner identity`);
  }

  const labels = await payerLabelFor(admin, record);
  const allocations =
    record.payments.payment_allocations.length > 0
      ? record.payments.payment_allocations.map((allocation) => ({
          label:
            allocation.label ??
            invoice.invoice_items.find((item) => item.kind === "charge")?.label ??
            "Fee charge",
          amountPaise: allocation.amount_paise,
        }))
      : [{ label: "Fee payment", amountPaise: record.payments.amount_paise }];

  const bytes = renderReceiptPdf({
    schoolName: "Faiz E Aam School",
    schoolContact: "Fee receipt - official record",
    receiptRef: record.reference,
    issuedAtIso: record.issued_at,
    invoiceRef: invoice.reference,
    studentLabel: labels.studentLabel,
    payerLabel: labels.payerLabel,
    amountPaise: record.payments.amount_paise,
    method: record.payments.method ?? "sandbox",
    gatewayRef: record.payments.provider_txn_id,
    status: invoice.status,
    allocations,
  });

  return {
    bytes,
    templateVersion: RECEIPT_TEMPLATE_VERSION,
    documentType: "receipt",
    checksum: checksumOf(bytes),
    sizeBytes: bytes.byteLength,
    sourceRecordId: record.id,
    sourceReference: record.reference,
    ownerDomain: "invoice",
    ownerRecordId: invoice.id,
    safeFilename: `receipt-${record.reference}.pdf`,
  };
}

type ReportRecord = {
  id: string;
  reference: string;
  student_id: string;
  student_reference: string;
  student_name: string;
  class_name: string;
  term: string;
  published_at: string;
  status: string;
  correction_note: string | null;
  rows: Array<{ subject: string; components: string; obtained: string; max: string; grade: string }>;
};

type ReportSnapshotMark = {
  component?: unknown;
  max?: unknown;
  obtained?: unknown;
  status?: unknown;
  markStatus?: unknown;
  remark?: unknown;
};

/** Map the immutable Slice 4 `snapshot.marks[]` shape into PDF table fields. */
export function mapReportCardSnapshot(snapshot: unknown, subject: string): { subject: string; components: string; obtained: string; max: string; grade: string } {
  const value = snapshot && typeof snapshot === "object" ? snapshot as Record<string, unknown> : {};
  const marks = Array.isArray(value.marks) ? value.marks as ReportSnapshotMark[] : [];
  const numeric = (input: unknown): number | null => typeof input === "number" && Number.isFinite(input) ? input : typeof input === "string" && input.trim() !== "" && Number.isFinite(Number(input)) ? Number(input) : null;
  if (marks.length === 0) {
    const obtained = numeric(value.obtained);
    const max = numeric(value.max);
    return {
      subject,
      components: "",
      obtained: obtained === null ? "-" : String(obtained),
      max: max === null ? "-" : String(max),
      grade: typeof value.grade === "string" ? value.grade : "-",
    };
  }
  let obtainedTotal = 0;
  let maxTotal = 0;
  let hasObtained = false;
  let hasMax = false;
  const components = marks.map((mark) => {
    const obtained = numeric(mark.obtained);
    const max = numeric(mark.max);
    if (obtained !== null) { obtainedTotal += obtained; hasObtained = true; }
    if (max !== null) { maxTotal += max; hasMax = true; }
    const component = typeof mark.component === "string" ? mark.component : "Component";
    const status = typeof mark.status === "string" ? mark.status : typeof mark.markStatus === "string" ? mark.markStatus : null;
    if (obtained !== null && max !== null) return `${component}: ${obtained}/${max}`;
    return `${component}: ${status ?? "-"}`;
  }).join("; ");
  return {
    subject,
    components,
    obtained: hasObtained ? String(obtainedTotal) : "-",
    max: hasMax ? String(maxTotal) : "-",
    grade: typeof value.grade === "string" ? value.grade : "-",
  };
}

async function resolveReportCard(admin: SupabaseClient<Database>, releaseRef: string): Promise<ReportRecord> {
  // This is a read-only provider boundary. The generated database type file is
  // refreshed from migrations in staging; keeping this nested projection
  // untyped here also lets local tests run against the pre-030 fixture type.
  const db = admin as unknown as SupabaseClient;
  const { data, error } = await db
    .from("result_report_releases")
    .select("id, reference, student_id, term, published_at, status, students(reference, people(display_name)), grade_sections(section_label, grades(label)), result_report_release_items(snapshot, subjects(name))")
    .eq("reference", releaseRef)
    .maybeSingle();
  if (error !== null) throw new PdfTransientError(`report release lookup failed: ${error.message}`);
  if (data === null) throw new Error(`Permanent: report release ${releaseRef} not found`);
  const record = data as {
    id: string;
    reference: string;
    student_id: string;
    term: string;
    published_at: string;
    status: string;
    students?: { reference?: string; people?: { display_name?: string } | null } | null;
    grade_sections?: { section_label?: string; grades?: { label?: string } | null } | null;
    result_report_release_items?: Array<{ snapshot?: unknown; subjects?: { name?: string } | null }>;
  };
  const rows = (record.result_report_release_items ?? []).map((item) => {
    return mapReportCardSnapshot(item.snapshot, item.subjects?.name ?? "Subject");
  });
  return {
    id: record.id,
    reference: record.reference,
    student_id: record.student_id,
    student_reference: record.students?.reference ?? record.student_id,
    student_name: record.students?.people?.display_name ?? "Student",
    class_name: record.grade_sections ? `${record.grade_sections.grades?.label ?? "Class"} ${record.grade_sections.section_label ?? ""}`.trim() : "Class",
    term: record.term,
    published_at: record.published_at,
    status: record.status,
    correction_note: null,
    rows,
  };
}

export async function generateReportCardPdf(
  admin: SupabaseClient<Database>,
  releaseRef: string,
): Promise<GeneratedPdf> {
  const record = await resolveReportCard(admin, releaseRef);
  const bytes = renderReportCardPdf({
    schoolName: "Faiz E Aam School",
    studentRef: record.student_reference,
    studentName: record.student_name,
    className: record.class_name,
    examLabel: record.term,
    publicationRef: record.reference,
    publishedAtIso: record.published_at,
    state: record.status,
    correctionNote: record.correction_note,
    rows: record.rows,
  });
  return {
    bytes,
    templateVersion: REPORT_CARD_TEMPLATE_VERSION,
    documentType: "report_card",
    checksum: checksumOf(bytes),
    sizeBytes: bytes.byteLength,
    sourceRecordId: record.id,
    sourceReference: record.reference,
    ownerDomain: "student",
    ownerRecordId: record.student_id,
    safeFilename: `report-card-${record.reference}.pdf`,
  };
}

/** Reserved private object key — source ids are opaque and never human refs. */
export function generatedObjectKey(sourceRecordId: string, checksum: string, documentType: "receipt" | "report_card" = "receipt"): string {
  return `generated/${documentType}/${sourceRecordId}/${checksum.slice(0, 32)}.pdf`;
}
