-- 000091 — Export catalog reseed.
--
-- Migration 000064 inserted the export domain catalogs once. A staging
-- data reset that truncates public tables removes those migration-seeded
-- reference rows, so this forward reseed restores them idempotently (the
-- statement upserts on the active domain key and is a no-op on a healthy
-- database).

insert into public.data_export_catalogs
  (domain, display_name, description, available_columns, required_filters, optional_filters, max_rows, is_active)
values
  ('students',
   'Students',
   'Student identity records with current enrollment placement.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"display_name","label":"Display name","type":"text"},
     {"column":"status","label":"Status","type":"text"},
     {"column":"school_student_number","label":"School student number","type":"text"},
     {"column":"enrollment_status","label":"Enrollment status","type":"text"},
     {"column":"grade_label","label":"Grade","type":"text"},
     {"column":"section_label","label":"Section","type":"text"},
     {"column":"academic_year_label","label":"Academic year","type":"text"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"status","label":"Status","type":"text"},
     {"filter":"academic_year_id","label":"Academic year","type":"uuid"},
     {"filter":"grade_section_id","label":"Grade section","type":"uuid"}]'::jsonb,
   50000, true),
  ('guardians',
   'Guardians',
   'Guardian identity records with linked children count.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"display_name","label":"Display name","type":"text"},
     {"column":"status","label":"Status","type":"text"},
     {"column":"linked_children_count","label":"Linked children","type":"number"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"status","label":"Status","type":"text"}]'::jsonb,
   50000, true),
  ('guardian_student_links',
   'Guardian–student links',
   'Verified guardian–student relationships.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"guardian_display_name","label":"Guardian","type":"text"},
     {"column":"student_display_name","label":"Student","type":"text"},
     {"column":"relationship_label","label":"Relationship","type":"text"},
     {"column":"status","label":"Status","type":"text"},
     {"column":"verification_source","label":"Verification source","type":"text"},
     {"column":"effective_from","label":"Effective from","type":"datetime"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"status","label":"Status","type":"text"},
     {"filter":"verification_source","label":"Verification source","type":"text"}]'::jsonb,
   50000, true),
  ('enrollments',
   'Enrollments',
   'Student placement in an academic year and grade/section.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"student_display_name","label":"Student","type":"text"},
     {"column":"grade_label","label":"Grade","type":"text"},
     {"column":"section_label","label":"Section","type":"text"},
     {"column":"academic_year_label","label":"Academic year","type":"text"},
     {"column":"status","label":"Status","type":"text"},
     {"column":"effective_from","label":"Effective from","type":"datetime"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"status","label":"Status","type":"text"},
     {"filter":"academic_year_id","label":"Academic year","type":"uuid"},
     {"filter":"grade_section_id","label":"Grade section","type":"uuid"}]'::jsonb,
   50000, true),
  ('admissions',
   'Admissions',
   'Admission applications and their current status.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"student_name","label":"Student name","type":"text"},
     {"column":"parent_name","label":"Parent name","type":"text"},
     {"column":"current_status","label":"Current status","type":"text"},
     {"column":"grade_label","label":"Grade","type":"text"},
     {"column":"academic_year_label","label":"Academic year","type":"text"},
     {"column":"submitted_at","label":"Submitted at","type":"datetime"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"current_status","label":"Current status","type":"text"},
     {"filter":"academic_year_id","label":"Academic year","type":"uuid"}]'::jsonb,
   50000, true),
  ('invoices',
   'Invoices',
   'Fee invoices with status and paid/outstanding amounts.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"student_display_name","label":"Student","type":"text"},
     {"column":"term","label":"Term","type":"text"},
     {"column":"status","label":"Status","type":"text"},
     {"column":"amount_paise","label":"Amount (paise)","type":"number"},
     {"column":"paid_paise","label":"Paid (paise)","type":"number"},
     {"column":"due_date","label":"Due date","type":"date"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"status","label":"Status","type":"text"},
     {"filter":"term","label":"Term","type":"text"},
     {"filter":"academic_year_id","label":"Academic year","type":"uuid"}]'::jsonb,
   50000, true),
  ('results',
   'Results',
   'Published assessment results with version and publication time.',
   '[{"column":"reference","label":"Reference","type":"text"},
     {"column":"student_display_name","label":"Student","type":"text"},
     {"column":"term","label":"Term","type":"text"},
     {"column":"status","label":"Status","type":"text"},
     {"column":"version","label":"Version","type":"number"},
     {"column":"published_at","label":"Published at","type":"datetime"}]'::jsonb,
   '[]'::jsonb,
   '[{"filter":"status","label":"Status","type":"text"},
     {"filter":"term","label":"Term","type":"text"},
     {"filter":"academic_year_id","label":"Academic year","type":"uuid"}]'::jsonb,
   50000, true)
on conflict (domain) where is_active = true
  do update set
    display_name      = excluded.display_name,
    description       = excluded.description,
    available_columns = excluded.available_columns,
    required_filters  = excluded.required_filters,
    optional_filters  = excluded.optional_filters,
    max_rows          = excluded.max_rows,
    is_active         = true,
    updated_at        = now();
